Create movie
rajtarovN/frontend pull request #3
Opened 2021-11-02 10:35 UTC by rajtarovN

2021-11-02 14:24 UTC, ivns1993 requested changes

2021-11-02 14:24 UTC, ivns1993 commented on src/App.js
> +        <CreateMovie></CreateMovie>
self closing tag

2021-11-02 14:24 UTC, ivns1993 commented on src/components/CreateMovie.js
> +const data = ["Action", "Horror", "Science fiction", "Comedy"]
ne mozemo da imamo hardkodovan niz, u prethodnom PRu sam ti napisala da napravis endpoint koji vraca listu svih zanrova, koristi to

2021-11-02 14:24 UTC, ivns1993 commented on src/components/CreateMovie.js
> +import axios from 'axios';
http service

2021-11-02 14:24 UTC, ivns1993 commented on src/components/CreateMovie.js
> +
redovi??

2021-11-02 14:24 UTC, ivns1993 commented on src/components/CreateMovie.js
> +    const [title, setTitle] = useState("");
indentacija treba da bude 2 space-a

2021-11-02 14:24 UTC, ivns1993 commented on src/components/CreateMovie.js
> +    const saveMovie = () =>{// ovo se poziva svaki put kada se promeni nesto, ne pomaze if, razmisliti
ovi komentari ne treba da budu tu ako hocemo da kreiramo pull request

2021-11-02 14:24 UTC, ivns1993 commented on src/components/CreateMovie.js
> +    const saveMovie = () =>{// ovo se poziva svaki put kada se promeni nesto, ne pomaze if, razmisliti
i razmak `const saveMovie = () => {` :D

2021-11-02 14:24 UTC, ivns1993 commented on src/components/CreateMovie.js
> +      const newMovie = {"id":0,
ne treba na frontu da izmisljamo id za novi film kada ga kreiramo

2021-11-02 14:24 UTC, ivns1993 commented on src/components/CreateMovie.js
> +                        "movie_genre":genre[0], //ovo nekako srediti
proslediti selektovani zanr

2021-11-02 14:24 UTC, ivns1993 commented on src/components/CreateMovie.js
> +                        "visited_num":0,
ovo ce kad se kreira uvek biti 0 tako da mozda ni ne moramo sa fronta da prosledjujemo, nego samo na backendu kazemo da je 0 kada kreiramo

2021-11-02 14:24 UTC, ivns1993 commented on src/components/CreateMovie.js
> +      const res=axios.post('http://127.0.0.1:8000/movies/', newMovie)
u movie servis dodamo metodu koja salje ovaj request (i koristi http servis)

2021-11-02 14:24 UTC, ivns1993 commented on src/components/CreateMovie.js
> +      console.log(res)
logove brisemo, ali verovatno hocemo neki hendler kad se posalje request zar ne, tj kada stigne response? tipa da se prebacimo na drugu stranu ili da prikazemo neku poruku i ispraznimo formu

2021-11-02 14:24 UTC, ivns1993 commented on src/components/CreateMovie.js
> +      <input id='image' onChange={e => setImage(e.target.value)} ></input><br/>
self closing tag za inpute

2021-11-04 10:24 UTC, ivns1993 commented on src/components/CreateMovie.js
> +    const res = axios.get('http://127.0.0.1:8000/genres')
pretpostavljam da cemo ove requestove slati iz nekog servisa a preko http servisa kad se umerga sve sto treba :D

2021-11-04 11:40 UTC, rajtarovN commented on src/components/CreateMovie.js
> +    const res = axios.get('http://127.0.0.1:8000/genres')
Da. :D

2021-11-09 08:33 UTC, ivns1993 commented on src/components/CreateMovie.js
> +    const newMovie = {"title" : title,
hajde da js object keys ne stavljamo pod navodnike ako nema potrebe :)

2021-11-09 08:33 UTC, ivns1993 commented on src/components/CreateMovie.js
> +    .then(function(data) {
i hajde da izaberemo async await sintaksu a ne mix toga i promise-a :D

2021-11-09 10:40 UTC, ivns1993 commented on src/components/CreateMovie.js
> +    const newMovie = { title, genre, description, image };
jel ok da bude samo genre? ranije je bilo movie_genre pa ne znam jel backend prilagodjen izmeni?

2021-11-09 10:41 UTC, ivns1993 approved these changes

2021-11-09 10:41 UTC, ivns1993 commented on src/components/CreateMovie.js
> +      alert("You made a new movie!")
imamo ove alerte i u servisu

2021-11-09 12:14 UTC, ivns1993 approved these changes

2021-11-09 13:02 UTC, merged